import Link from 'next/link';import {sql} from '@vercel/postgres';import {seedProducts} from '@/lib/database';export const dynamic='force-dynamic';
export default async function Home(){await seedProducts();const{rows:products}=await sql`SELECT * FROM products WHERE active=true ORDER BY featured DESC,created_at DESC`;return <main><div className="announcement">Free delivery across Egypt · Cash on delivery · Bundle & save when you buy 2+</div><nav className="nav container"><Link href="/" className="brand">WEYVO</Link><div className="navlinks"><a href="#shop">Shop</a><a href="#offers">Offers</a><a href="#story">Our story</a><Link href="/admin/login">Admin</Link></div></nav>
<section className="hero container reveal"><div className="hero-copy"><div className="eyebrow">THE EVERYDAY WALLET, REFINED</div><h1>Carry less.<br/><em>Live more.</em></h1><p>A premium slim wallet built for everyday life — clean lines, RFID protection, smart NFC options and a finish that feels expensive without the luxury markup.</p><div className="hero-actions"><a className="btn" href="#shop">Shop wallets</a><a className="text-link" href="#video">See it in motion →</a></div><div className="hero-proof"><span>★★★★★</span><span>Premium feel · everyday price</span></div></div><div className="hero-visual"><img src="/hero.jpg" alt="WEYVO Smart Wallet"/><div className="floating-card"><b>649 EGP</b><span>Premium smart wallet</span></div></div></section>
<section id="video" className="cinematic-video reveal"><video autoPlay muted loop playsInline preload="metadata" poster="/hero.jpg"><source src="/wallet-video.mp4" type="video/mp4"/></video><div className="video-overlay"><div className="eyebrow">SEE THE DIFFERENCE</div><h2>Small wallet.<br/><em>Big upgrade.</em></h2><a className="btn light" href="#shop">Choose yours</a></div></section>
<section className="marquee"><div>SLIM PROFILE · RFID PROTECTION · PREMIUM FINISH · NFC OPTION · FREE DELIVERY · CASH ON DELIVERY · SLIM PROFILE · RFID PROTECTION · PREMIUM FINISH · NFC OPTION · </div></section>
<section id="offers" className="container section offers-section"><div className="section-head reveal"><div><div className="eyebrow">BUY MORE. SAVE MORE.</div><h2>Better together.</h2></div><span>Automatic discount at checkout</span></div><div className="offer-grid"><div className="offer-card reveal"><span>01</span><h3>Buy 1</h3><strong>649 EGP</strong><p>Perfect for your everyday carry.</p></div><div className="offer-card featured-offer reveal"><span>02 · BEST VALUE</span><h3>Buy 2</h3><strong>8% OFF</strong><p>Two wallets, more style, less total.</p></div><div className="offer-card reveal"><span>03</span><h3>Buy 3+</h3><strong>12% OFF</strong><p>Build a set for you and your people.</p></div></div></section>
<section id="shop" className="container section shop-section"><div className="section-head reveal"><div><div className="eyebrow">SHOP THE COLLECTION</div><h2>Made to go everywhere.</h2></div><span>{products.length} products</span></div><div className="product-grid">{products.map((p:any)=><Link className="product-card reveal" key={p.id} href={`/products/${p.slug}`}><div className="product-image">{p.compare_price&&p.compare_price>p.price&&<span className="sale">SALE</span>}<img src={p.images?.[0]||'/hero.jpg'} alt={p.name}/><span className="quick">View product →</span></div><div className="product-meta"><div><h3>{p.name}</h3><p>{p.category}</p></div><div className="product-price-small">{p.price.toLocaleString()} EGP {p.compare_price&&<del>{p.compare_price.toLocaleString()}</del>}</div></div></Link>)}</div></section>
<section className="editorial-split reveal"><div className="editorial-image"><img src="/open.jpg" alt="WEYVO wallet open with cards"/></div><div className="editorial-copy"><div className="eyebrow">DESIGNED FOR REAL LIFE</div><h2>Looks premium.<br/><em>Works harder.</em></h2><p>Enough room for what you need, without the brick in your pocket. Add NFC when you want a digital identity built into your wallet.</p><a className="text-link" href="#shop">Explore the collection →</a></div></section>
<section id="story" className="story-banner reveal"><div className="container story-inner"><div><div className="eyebrow">WHY WEYVO</div><h2>Minimal outside.<br/>Thoughtful inside.</h2></div><p>We believe everyday products should solve a problem without adding noise. WEYVO combines a slim silhouette with practical card storage, RFID protection and optional smart contact sharing.</p></div></section>
<section className="container section feature-section"><div className="features"><div className="feature reveal"><span>01</span><h3>Ultra slim</h3><p>Less bulk in your pocket, more room for the things that matter.</p></div><div className="feature reveal"><span>02</span><h3>RFID protected</h3><p>An added layer of protection for your contactless cards.</p></div><div className="feature reveal"><span>03</span><h3>NFC optional</h3><p>Choose the smart version only if you actually need it.</p></div></div></section>
<section className="container visual-section reveal"><div className="visual-copy"><div className="eyebrow">SEE THE DETAILS</div><h2>Designed to be noticed.<br/>Built to be used.</h2></div><div className="visual-grid"><img src="/open.jpg" alt="Open wallet"/><img src="/cards.jpg" alt="Wallet cards"/><img src="/nfc.jpg" alt="Wallet NFC detail"/></div></section>
<footer className="footer"><div className="container"><div className="brand">WEYVO</div><p>Premium everyday carry, designed in Egypt.</p><span>© 2026 WEYVO</span></div></footer></main>}
