'use client';
import {useEffect,useRef,useState} from 'react';
type Lang='en'|'ar';

const translations:Record<string,string>={
'FREE DELIVERY ACROSS EGYPT':'شحن مجاني داخل مصر','CASH ON DELIVERY':'الدفع عند الاستلام','BUY 2+ & SAVE':'اشتري 2 أو أكتر ووفر','PREMIUM HANDMADE LEATHER':'جلد فاخر مصنوع بعناية','Shop':'المنتجات','Offers':'العروض','Our story':'قصتنا','Admin':'الإدارة','SEE THE DIFFERENCE':'شوف الفرق','Small wallet.':'محفظة صغيرة.','Big upgrade.':'فرق كبير.','Choose yours':'اختار محفظتك','Scroll to explore':'اسحب واكتشف','BUY MORE. SAVE MORE.':'كل ما تشتري أكتر، توفر أكتر','Better together.':'اختيارات أوفر ليك.','Automatic discount at checkout':'الخصم بيتحسب تلقائيًا عند إتمام الطلب',
'Buy 1':'محفظة واحدة','Buy 2':'محفظتين','Buy 3':'3 محافظ','01 · BEST VALUE':'01 · أفضل اختيار','02 · BEST VALUE':'02 · أفضل قيمة','03 · BEST SAVING':'03 · أكبر توفير','One wallet for your everyday carry.':'محفظة خفيفة لكل يوم.','Save 99 EGP · 349.5 EGP each.':'وفر 99 جنيه · 349.5 جنيه للمحفظة.','Save 248 EGP · 316 EGP each.':'وفر 248 جنيه · 316 جنيه للمحفظة.','SHOP THE COLLECTION':'اختار محفظتك','Made to go everywhere.':'مصممة تكون معاك في كل مكان.','View product →':'شوف التفاصيل ←','DESIGNED FOR REAL LIFE':'مصممة ليومك','Looks premium.':'شكل فاخر.','Works harder.':'وعملية أكتر.','Explore the collection →':'اكتشف المجموعة ←','WHY WEYVO':'ليه WEYVO؟','Minimal outside.':'بسيطة من بره.','Thoughtful inside.':'كل تفصيلة ليها سبب.','Ultra slim':'رفيعة جدًا','RFID protected':'حماية RFID','NFC optional':'NFC اختياري','SEE THE DETAILS':'شوف التفاصيل','Designed to be noticed.':'شكل يلفت النظر.','Built to be used.':'وعملية في الاستخدام.','Premium everyday carry, designed in Egypt.':'إكسسوار يومي فاخر، مصمم في مصر.','products':'منتجات',
'FAST CHECKOUT':'إتمام طلب سريع','Complete your order':'كمل طلبك','Contact':'بياناتك','Delivery':'التوصيل','Payment':'الدفع','Confirm':'التأكيد','Who are we delivering to?':'هنوصل لمين؟','Just your name and phone — that’s it.':'اسمك ورقم تليفونك بس — وخلاص.','Full name *':'الاسم بالكامل *','Phone *':'رقم التليفون *','Your name':'اسمك','Continue →':'كمل ←','Where should we deliver?':'هنوصل فين؟','Your selected quantity and NFC version are already saved.':'الكمية واختيار NFC محفوظين بالفعل.','Delivery address *':'عنوان التوصيل *','City, area, street, building, apartment...':'المحافظة، المنطقة، الشارع، العمارة، الشقة...','Color':'اللون','Selected order':'طلبك','Wallet':'محفظة','Wallets':'محافظ','Standard':'العادية','Smart NFC':'NFC الذكية','Add a note (optional)':'أضف ملاحظة (اختياري)','Hide note':'إخفاء الملاحظة','Almost done.':'فاضل خطوة أخيرة.','Everything is selected. Just review your order and place it.':'كل حاجة اتحددت. راجع طلبك وأكّد الطلب.','Choose payment':'اختار طريقة الدفع','Pay online with InstaPay or choose cash on delivery.':'ادفع عن طريق InstaPay أو اختار الدفع عند الاستلام.','Cash on Delivery':'الدفع عند الاستلام','Pay when your order arrives':'ادفع لما طلبك يوصلك','InstaPay':'InstaPay','Upload payment screenshot':'ارفع صورة التحويل','Review order →':'راجع الطلب ←','Place order —':'تأكيد الطلب —','Order confirmed ✓':'تم تأكيد الطلب ✓','saved successfully.':'اتحفظ بنجاح.','Total:':'الإجمالي:','Payment:':'طريقة الدفع:','Send order on WhatsApp':'ابعت الطلب على واتساب',
'CUSTOMER ACCOUNT':'حساب العميل','Welcome back.':'أهلًا بيك تاني.','Create your account.':'اعمل حسابك.','Sign in to keep your WEYVO orders and details in one place.':'سجّل دخولك عشان تتابع طلباتك وبياناتك في مكان واحد.','Create an account for a faster checkout and easier order tracking.':'اعمل حساب عشان تكمّل طلبك أسرع وتتابع طلباتك بسهولة.','Email':'البريد الإلكتروني','Password':'كلمة المرور','Sign in':'تسجيل الدخول','Create account':'إنشاء حساب','New to WEYVO? Create an account':'أول مرة مع WEYVO؟ اعمل حساب','Already have an account? Sign in':'عندك حساب؟ سجّل الدخول','Admin login':'دخول الإدارة','Back':'رجوع',
'BUY NOW':'اطلب الآن','Premium leather':'جلد فاخر','Fast delivery':'توصيل سريع','Choose quantity':'اختار الكمية','Choose your version':'اختار النسخة','No NFC chip':'بدون NFC','Digital profile · +100 / wallet':'بروفايل رقمي · +100 جنيه للمحفظة','MOST POPULAR':'الأكثر طلبًا','Your quantity and NFC choice will be saved automatically at checkout.':'الكمية واختيار NFC هيتحفظوا تلقائيًا عند إتمام الطلب.',
'Folder-inspired design':'تصميم مستوحى من الفولدر','Storage solution':'مساحة منظمة لكروتك','Slim card storage':'مساحة للكروت بدون حجم زيادة','NFC — share with a tap':'NFC — شارك بياناتك بلمسة','Minimal design. Smart technology. Everyday carry.':'تصميم بسيط. تقنية ذكية. استخدام يومي.','A folder-inspired silhouette built around your essentials.':'تصميم عملي مستوحى من الفولدر، معمول لأساسياتك.','WEYVO / Wallets':'WEYVO / محافظ','5 customer reviews':'5 تقييمات من العملاء','customer reviews':'تقييمات العملاء','1 Wallet':'محفظة واحدة','2 Wallets':'محفظتين','3 Wallets':'3 محافظ','Standard wallet':'المحفظة العادية','NFC version':'نسخة NFC','Add to cart':'أضف للطلب','Order now':'اطلب دلوقتي','Choose color':'اختار اللون','Black':'أسود','Brown':'بني','Yellow':'أصفر','Beige':'بيج','Quantity':'الكمية','Subtotal':'الإجمالي الفرعي','Shipping':'الشحن','Free':'مجاني','Total':'الإجمالي','Place your order':'أكد طلبك','Order details':'تفاصيل الطلب','Customer details':'بيانات العميل','Delivery details':'بيانات التوصيل'};

const normalize=(s:string)=>s.replace(/\s+/g,' ').trim();
const entries=Object.entries(translations);

function translateNode(root:HTMLElement,lang:Lang){
 const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);const nodes:Text[]=[];let n;
 while(n=walker.nextNode())nodes.push(n as Text);
 nodes.forEach(t=>{const raw=t.nodeValue||'';const key=normalize(raw);if(!key)return;if(lang==='ar'){const v=translations[key];if(v)t.nodeValue=raw.replace(key,v)}else{const reverse=entries.find(([,v])=>normalize(v)===key)?.[0];if(reverse)t.nodeValue=raw.replace(key,reverse)}});
 root.querySelectorAll<HTMLInputElement|HTMLTextAreaElement>('input,textarea').forEach(el=>{const p=el.getAttribute('placeholder');if(!p)return;const key=normalize(p);if(lang==='ar'&&translations[key])el.placeholder=translations[key];else if(lang==='en'){const reverse=entries.find(([,v])=>normalize(v)===key)?.[0];if(reverse)el.placeholder=reverse}});
}

export default function LanguageSwitcher(){
 const[lang,setLang]=useState<Lang>('en');const langRef=useRef<Lang>('en');
 useEffect(()=>{const saved=localStorage.getItem('weyvo-lang') as Lang|null;const browser=(navigator.language||'en').toLowerCase();const initial=saved==='ar'||saved==='en'?saved:(browser.startsWith('ar')?'ar':'en');langRef.current=initial;setLang(initial);apply(initial);const obs=new MutationObserver(()=>translateNode(document.body,langRef.current));obs.observe(document.body,{childList:true,subtree:true});return()=>obs.disconnect()},[]);
 function apply(l:Lang){document.documentElement.lang=l;document.documentElement.dir=l==='ar'?'rtl':'ltr';document.body.dir=l==='ar'?'rtl':'ltr';translateNode(document.body,l)}
 function toggle(){const next:Lang=langRef.current==='en'?'ar':'en';langRef.current=next;setLang(next);localStorage.setItem('weyvo-lang',next);apply(next)}
 return <button type="button" onClick={toggle} aria-label="Change language" className="language-switcher">{lang==='en'?'العربية':'English'}<style jsx>{`
 .language-switcher{position:fixed;right:14px;bottom:calc(104px + env(safe-area-inset-bottom));z-index:100000;border:1px solid #dedbd6;background:#111;color:#fff;border-radius:999px;padding:9px 14px;font-size:11px;font-weight:800;letter-spacing:.2px;line-height:1;box-shadow:0 8px 24px rgba(0,0,0,.16);cursor:pointer;touch-action:manipulation;pointer-events:auto;white-space:nowrap;direction:ltr;unicode-bidi:isolate}
 .language-switcher:hover{transform:translateY(-1px)}
 html[dir='rtl'] .language-switcher{right:auto;left:14px}
 @media(max-width:560px){.language-switcher{right:14px;bottom:calc(104px + env(safe-area-inset-bottom));padding:9px 13px;font-size:10px}html[dir='rtl'] .language-switcher{right:auto;left:14px}}
 `}</style></button>;
}