'use client';
import {useEffect,useState} from 'react';

type Lang='en'|'ar';
const translations:Record<string,string>={
'FREE DELIVERY ACROSS EGYPT':'شحن مجاني داخل مصر','CASH ON DELIVERY':'الدفع عند الاستلام','BUY 2+ & SAVE':'اشتري 2 أو أكثر ووفر','PREMIUM HANDMADE LEATHER':'جلد فاخر مصنوع بعناية',
'Shop':'المنتجات','Offers':'العروض','Our story':'قصتنا','Admin':'الإدارة','SEE THE DIFFERENCE':'شوف الفرق','Small wallet.':'محفظة صغيرة.','Big upgrade.':'تطوير كبير.','Choose yours':'اختار محفظتك','Scroll to explore':'اسحب للاستكشاف','SLIM PROFILE · RFID PROTECTION · PREMIUM FINISH · NFC OPTION · FREE DELIVERY · CASH ON DELIVERY ·':'تصميم نحيف · حماية RFID · تشطيب فاخر · خيار NFC · شحن مجاني · الدفع عند الاستلام ·',
'BUY MORE. SAVE MORE.':'اشتري أكتر ووفر أكتر','Better together.':'أحلى مع بعض.','Automatic discount at checkout':'الخصم بيتحسب تلقائيًا عند إتمام الطلب','Buy 1':'اشتري 1','Buy 2':'اشتري 2','Buy 3':'اشتري 3','01 · BEST VALUE':'01 · أفضل قيمة','02 · BEST VALUE':'02 · أفضل قيمة','03 · BEST SAVING':'03 · أكبر توفير','One wallet for your everyday carry.':'محفظة واحدة لاستخدامك اليومي.','Save 99 EGP · 349.5 EGP each.':'وفر 99 جنيه · 349.5 جنيه للمحفظة.','Save 248 EGP · 316 EGP each.':'وفر 248 جنيه · 316 جنيه للمحفظة.','SHOP THE COLLECTION':'تسوق المجموعة','Made to go everywhere.':'مصممة تروح معاك كل مكان.','View product →':'شوف المنتج ←','DESIGNED FOR REAL LIFE':'مصممة للحياة اليومية','Looks premium.':'شكل فاخر.','Works harder.':'وأداء عملي.','Explore the collection →':'اكتشف المجموعة ←','WHY WEYVO':'ليه WEYVO؟','Minimal outside.':'بسيطة من الخارج.','Thoughtful inside.':'مدروسة من الداخل.','Ultra slim':'رفيعة جدًا','RFID protected':'حماية RFID','NFC optional':'NFC اختياري','SEE THE DETAILS':'شوف التفاصيل','Designed to be noticed.':'مصممة تلفت النظر.','Built to be used.':'ومصممة للاستخدام.','Premium everyday carry, designed in Egypt.':'منتجات يومية فاخرة، مصممة في مصر.',
'FAST CHECKOUT':'إتمام طلب سريع','Complete your order':'كمل طلبك','Contact':'بياناتك','Delivery':'التوصيل','Payment':'الدفع','Confirm':'التأكيد','Who are we delivering to?':'هنوصل لمين؟','Just your name and phone — that’s it.':'اسمك ورقم تليفونك بس — وخلاص.','Full name *':'الاسم بالكامل *','Phone *':'رقم التليفون *','Your name':'اسمك','Continue →':'كمل →','Where should we deliver?':'هنوصل فين؟','Your selected quantity and NFC version are already saved.':'الكمية واختيار NFC محفوظين بالفعل.','Delivery address *':'عنوان التوصيل *','City, area, street, building, apartment...':'المحافظة، المنطقة، الشارع، العمارة، الشقة...','Color':'اللون','Selected order':'طلبك المختار','Wallet':'محفظة','Wallets':'محافظ','Standard':'عادية','Smart NFC':'NFC ذكية','Add a note (optional)':'أضف ملاحظة (اختياري)','Hide note':'إخفاء الملاحظة','Almost done.':'فاضل خطوة أخيرة.','Everything is selected. Just review your order and place it.':'كل حاجة اتحددت. راجع طلبك واضغط تأكيد.','Choose payment':'اختار طريقة الدفع','Pay online with InstaPay or choose cash on delivery.':'ادفع أونلاين عن طريق InstaPay أو اختار الدفع عند الاستلام.','Cash on Delivery':'الدفع عند الاستلام','Pay when your order arrives':'ادفع لما طلبك يوصلك','InstaPay':'InstaPay','Upload payment screenshot':'ارفع صورة التحويل','Review order →':'راجع الطلب →','Place order —':'تأكيد الطلب —','Order confirmed ✓':'تم تأكيد طلبك ✓','Order':'الطلب','saved successfully.':'اتحفظ بنجاح.','Total:':'الإجمالي:','Payment:':'الدفع:','Send order on WhatsApp':'ابعت الطلب على واتساب','CUSTOMER ACCOUNT':'حساب العميل','Welcome back.':'أهلًا بيك تاني.','Create your account.':'اعمل حسابك.','Sign in to keep your WEYVO orders and details in one place.':'سجل دخولك لمتابعة طلباتك وبياناتك مع WEYVO.','Create an account for a faster checkout and easier order tracking.':'اعمل حساب عشان إتمام الطلب يبقى أسرع وتتابع طلباتك بسهولة.','Email':'الإيميل','Password':'كلمة المرور','Sign in':'تسجيل الدخول','Create account':'إنشاء حساب','New to WEYVO? Create an account':'جديد مع WEYVO؟ اعمل حساب','Already have an account? Sign in':'عندك حساب؟ سجل الدخول','Admin login':'دخول الإدارة','Back':'رجوع','BUY NOW':'اطلب الآن'
};
const normalize=(s:string)=>s.replace(/\s+/g,' ').trim();
function translateNode(root:HTMLElement,lang:Lang){
 const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);const nodes:Text[]=[];let n;while(n=walker.nextNode())nodes.push(n as Text);
 nodes.forEach(t=>{const raw=t.nodeValue||'';const key=normalize(raw);if(!key||translations[key]===undefined)return;if(lang==='ar')t.nodeValue=raw.replace(key,translations[key]);else{const reverse=Object.entries(translations).find(([,v])=>normalize(v)===key)?.[0];if(reverse)t.nodeValue=raw.replace(key,reverse)}});
 root.querySelectorAll<HTMLInputElement|HTMLTextAreaElement>('input,textarea').forEach(el=>{const p=el.getAttribute('placeholder');if(!p)return;const key=normalize(p);if(lang==='ar'&&translations[key])el.placeholder=translations[key];else if(lang==='en'){const reverse=Object.entries(translations).find(([,v])=>normalize(v)===key)?.[0];if(reverse)el.placeholder=reverse}});
}
export default function LanguageSwitcher(){const[lang,setLang]=useState<Lang>('en');useEffect(()=>{const saved=localStorage.getItem('weyvo-lang') as Lang|null;const browser=(navigator.language||'en').toLowerCase();const initial=saved==='ar'||saved==='en'?saved:(browser.startsWith('ar')?'ar':'en');setLang(initial);apply(initial);const obs=new MutationObserver(()=>apply(initial));obs.observe(document.body,{childList:true,subtree:true});return()=>obs.disconnect()},[]);function apply(l:Lang){document.documentElement.lang=l;document.documentElement.dir=l==='ar'?'rtl':'ltr';document.body.dir=l==='ar'?'rtl':'ltr';translateNode(document.body,l)}function toggle(){const next:Lang=lang==='en'?'ar':'en';setLang(next);localStorage.setItem('weyvo-lang',next);apply(next)}return <button type="button" onClick={toggle} aria-label="Change language" className="language-switcher">{lang==='en'?'العربية':'English'}</button>}
